/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.des.produit;

import gestion.des.produit.dao.ConnectDB;
import gestion.des.produit.modele.Achat;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ziram
 */
public class AchatForm extends javax.swing.JFrame {

    /**
     * Creates new form AchatForm
     */
    public AchatForm() {
        initComponents();icon();
    }
    void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("Cartgrill_icon-icons.com_51191.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();

        setTitle("les achats");
        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(1300, 880));
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 229, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 36, 110)));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jButton6.setBackground(new java.awt.Color(182, 36, 110));
        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/imprimer-icone-3918-48.png"))); // NOI18N
        jButton6.setText("imprimer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(680, 310, 150, 57);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/1499142915_sign-add.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel12.setDisabledIcon(null);
        jLabel12.setName("ajouter"); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(369, 37, 48, 48);
        jLabel12.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel1.setText("id");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(36, 13, 17, 26);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(163, 12, 186, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel2.setText("nom prenom forn");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1, 54, 149, 26);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel3.setText(" \tdesignation");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 104, 105, 26);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(164, 103, 208, 30);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(163, 51, 186, 34);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel4.setText("quantité");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(19, 154, 70, 26);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(164, 153, 208, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel5.setText("prix totale");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(19, 251, 105, 26);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(164, 250, 208, 30);

        jButton1.setBackground(new java.awt.Color(182, 36, 110));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/ajouter.png"))); // NOI18N
        jButton1.setText("ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(28, 324, 150, 41);

        jButton2.setBackground(new java.awt.Color(182, 36, 110));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/supprimer.png"))); // NOI18N
        jButton2.setText("supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(340, 322, 150, 44);

        jButton4.setBackground(new java.awt.Color(182, 36, 110));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/User-Files-icon.png"))); // NOI18N
        jButton4.setText("modifier");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(184, 322, 150, 44);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nom_prenom_forn", "designation", "date_achat" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(660, 180, 189, 34);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(660, 230, 250, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/viewmag--icone-5948-32.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(850, 180, 40, 35);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel6.setText("date debut");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(930, 230, 81, 24);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel7.setText("date fin");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(930, 270, 59, 24);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " N_achat", " 	nom_prenom_forn", " 	designation", "quantité", " prix_total", "prix_unitaire", " date_achat"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 204, 204));
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(2);
        jTable1.setSelectionBackground(new java.awt.Color(182, 36, 110));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue(" N_achat");
            jTable1.getColumnModel().getColumn(1).setHeaderValue(" \tnom_prenom_forn");
            jTable1.getColumnModel().getColumn(2).setHeaderValue(" \tdesignation");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("quantité");
            jTable1.getColumnModel().getColumn(4).setHeaderValue(" prix_total");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("prix_unitaire");
            jTable1.getColumnModel().getColumn(6).setHeaderValue(" date_achat");
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(28, 377, 1160, 270);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("prix totale achat :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 650, 173, 57);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(240, 650, 320, 57);

        jButton3.setBackground(new java.awt.Color(182, 36, 110));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/modifier.png"))); // NOI18N
        jButton3.setText("actualliser");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(496, 322, 150, 44);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 51));
        jLabel10.setText(".");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(680, 110, 296, 29);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 51));
        jLabel11.setText(".");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(680, 80, 296, 29);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel13.setText("prix unitaite");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(19, 201, 105, 32);

        jTextField8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(164, 203, 208, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/001-technology.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14);
        jLabel14.setBounds(376, 199, 32, 32);

        jLabel15.setText("-");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(380, 280, 50, 14);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("TVA");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(442, 250, 24, 17);
        jPanel1.add(jSpinner1);
        jSpinner1.setBounds(382, 250, 50, 30);

        jButton7.setBackground(new java.awt.Color(182, 36, 110));
        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/annuler-icone-6802-48.png"))); // NOI18N
        jButton7.setText("vider");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(1020, 650, 150, 57);

        jButton8.setBackground(new java.awt.Color(182, 36, 110));
        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/simulateur-argent-icone-5481-48.png"))); // NOI18N
        jButton8.setText("Exporte");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(1020, 310, 150, 57);

        jButton16.setBackground(new java.awt.Color(182, 36, 110));
        jButton16.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/index-up-upload-icone-7700-32.png"))); // NOI18N
        jButton16.setText("Importe");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(850, 310, 150, 59);

        jDateChooser3.setForeground(new java.awt.Color(204, 255, 255));
        jDateChooser3.setDateFormatString("yyyy-MM-dd ");
        jDateChooser3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.add(jDateChooser3);
        jDateChooser3.setBounds(1020, 270, 142, 33);

        jDateChooser4.setForeground(new java.awt.Color(204, 255, 255));
        jDateChooser4.setDateFormatString("yyyy-MM-dd ");
        jDateChooser4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.add(jDateChooser4);
        jDateChooser4.setBounds(1020, 230, 142, 33);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/about3.png"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(0, 0, 1360, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1362, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
ConnectDB db;
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //jLabel8.setText(db.AllAchat(jTable1)+" DA");
          
        jDateChooser4.setVisible(false);
       jDateChooser3.setVisible(false);
       jLabel6.setVisible(false);  jLabel7.setVisible(false);
        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
db=new ConnectDB();db.ConnexionIntoDataBase();
        db.FindNomPrenomFornis(jComboBox1);
        jLabel8.setText(db.AllAchat(jTable1)+" DA");
        jLabel10.setText("pt "+jLabel8.getText());
        
    }//GEN-LAST:event_formWindowOpened

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        db.AllAchat(jTable1);jLabel10.setText("");jLabel11.setText("");
        jTextField2.setText("");jLabel10.setText("pt "+jLabel8.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i;
        try{
           
            i= jTable1.getSelectedRow();
            jTextField1.setText( jTable1.getValueAt(i, 0)+"");
            jTextField3.setText( jTable1.getValueAt(i, 2)+"");
            jTextField4.setText( jTable1.getValueAt(i, 3)+"");
            jTextField5.setText( jTable1.getValueAt(i, 4)+"");
            jTextField8.setText( jTable1.getValueAt(i, 5)+"");
            jComboBox1.setSelectedItem(jTable1.getValueAt(i, 1) + "");


        }catch(Exception e){

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{         //db.DeleteAllElementTab(jTable1, 6, 89);
            
             SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
            db.FindAchat(jTable1, jComboBox2.getSelectedItem()+"", jTextField2.getText(),
                jLabel11,jLabel10);
            if(jComboBox2.getSelectedItem().equals("date_achat")){
                // db.DeleteAllElementTab(jTable1, 6, 89);
                jTextField2.setVisible(false);
                db.FindAchatDate(jTable1, sdf.format(jDateChooser4.getDate()), sdf.format(jDateChooser3.getDate()) ,jLabel11,
                    jLabel10);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "ereur operation");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if(jComboBox2.getSelectedItem().equals("date_achat")) {
            jDateChooser4.setVisible(true);
            jDateChooser3.setVisible(true);
            jLabel6.setVisible(true);  jLabel7.setVisible(true); jTextField2.setVisible(false);
            /*  jTextField2.setText("");*/jLabel10.setText("");jLabel11.setText("");
        }   else{
            jDateChooser4.setVisible(false);
            jDateChooser3.setVisible(false);
            jLabel6.setVisible(false);  jLabel7.setVisible(false);
            jTextField2.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{ Achat ach=new Achat(0,jComboBox1.getSelectedItem()+"", jTextField3.getText(),
            Integer.parseInt(jTextField4.getText()) ,Float.parseFloat(jTextField5.getText()), 0,
            null);
        db.UpdatAchat(Integer.parseInt(jTextField1.getText()), ach);
        jLabel8.setText(db.AllAchat(jTable1)+" DA");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "eruer operation");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{  if(JOptionPane.showConfirmDialog(null, "confirmer la supression ?", "suppression"
            ,JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
        db.DeleteAchat(Integer.parseInt(jTextField1.getText()));
        //   db.DeleteAllElementTab(jTable1, 6, 89);
        jLabel8.setText( db.AllAchat(jTable1)+" DA");

        }}catch(HeadlessException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, "ereur operation");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{  Achat ach=new Achat(0,jComboBox1.getSelectedItem()+""
            , jTextField3.getText(),Integer.parseInt(jTextField4.getText()) , Float.parseFloat(jTextField5.getText()), 0,db.showDate());
        db.inserAchat(ach);jLabel8.setText(db.AllAchat(jTable1)+" DA");
        jLabel10.setText("pt "+jLabel8.getText());
          JOptionPane.showMessageDialog(null, "Le produit est ajoute MERCIE <3");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "ereur de saisis");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        Forniseur_Client fc=new Forniseur_Client();fc.setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        MessageFormat Header=new MessageFormat("les achats"
            + " "+db.showDateTime()+"\n "+jLabel10.getText());

        MessageFormat footer=new MessageFormat("page{0,number,integer}");
        try {

            jTable1.print(JTable.PrintMode.FIT_WIDTH, Header, footer );

        } catch (java.awt.print.PrinterException ex) {
            System.err.format("ereur dimpression",ex.getMessage());
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
       float qt = Float.parseFloat(jTextField4.getText());
       float un = Float.parseFloat(jTextField8.getText());
       int t = (int) jSpinner1.getValue();
       float r = qt*un ; 
          System.out.println(t);
          jLabel15.setText((r*t)/100 + "");
          jTextField5.setText(((r*t)/100)+ r +"");
       

           
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
            if (JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer tout le tableau de Achat ?", "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
              { db.clear("achat");
              }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         try {
            ExcelExporter ex =new ExcelExporter();
            File f =  new File("achats.xls");
             try (FileWriter fw = new FileWriter("achats.csv")) {
                 String sql="select * from achat";
                 db.csvachatfac(sql , fw);
                 fw.flush();
             }
            ex.exportTable(jTable1, f);
              JOptionPane.showMessageDialog(null, "operation Done"," Done", 
                  JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex1) {
            Logger.getLogger(VenteForm.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        try {
            // TODO add your handling code here:
            JFileChooser file =new JFileChooser();
            file.setFileFilter(new FileNameExtensionFilter("csv file","csv"));
            file.showSaveDialog(this);
            File f = file.getSelectedFile();
            String path = f.getAbsolutePath();
            BufferedReader reader = new BufferedReader(new FileReader(path));

            while( reader.readLine() !=null){
            db.importeachat(reader.readLine());
            }
                JOptionPane.showMessageDialog(null, "operation Done"," Done", 
                  JOptionPane.INFORMATION_MESSAGE);
            
        } catch (IOException ex) {
            Logger.getLogger(AchatForm.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AchatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AchatForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
