/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.des.produit;
import gestion.des.produit.dao.ConnectDB;
import gestion.des.produit.modele.User;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/**
 *
 * @author ziram
 */
public final class AjouteUser extends javax.swing.JFrame {

    /**
     * Creates new form AjouteUser
     */
    public AjouteUser() {
        initComponents();
        icon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setTitle("Ajoute user");
        setBackground(new java.awt.Color(255, 229, 247));
        setFocusCycleRoot(false);
        setForeground(new java.awt.Color(0, 102, 102));
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(410, 420));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setActionCommand("<Not Set>");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 198, 156, 50);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(30, 277, 156, 50);

        jCheckBox1.setActionCommand("Super User");
        jCheckBox1.setLabel("Super User");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(0, 336, 180, 23);

        jButton1.setBackground(new java.awt.Color(182, 36, 110));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/nouveau.png"))); // NOI18N
        jButton1.setText("Ajoute");
        jButton1.setToolTipText("ajoute");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(232, 227, 160, 68);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(182, 36, 110));
        jLabel1.setText("Ajoute an User");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 139, 184, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 175, 78, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 254, 67, 17);

        jCheckBox2.setText("Achat");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(232, 336, 100, 23);

        jCheckBox3.setText("Stock");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(232, 313, 100, 23);

        jCheckBox4.setText("Facture");
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(232, 359, 100, 23);

        jLabel4.setText("Autorisation d'utilisateur");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(232, 298, 160, 14);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Name"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(182, 36, 110));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(4, 11, 220, 122);

        jButton2.setBackground(new java.awt.Color(182, 36, 110));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/supprimer.png"))); // NOI18N
        jButton2.setText("Supprime");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(242, 46, 150, 62);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 140, 410, 2);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/about.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 410, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents
void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("Cartgrill_icon-icons.com_51191.png")));
    }
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       try{
        
        db = new ConnectDB();
        db.ConnexionIntoDataBase();
        User user = new User();
           user.setnom_prenom_user(jTextField1.getText());
           user.setpassword(jTextField2.getText());
           if(jCheckBox1.isSelected()){
           user.setgrad(1);}
           else if(jCheckBox2.isSelected() || jCheckBox3.isSelected() || jCheckBox4.isSelected() ){
            if(jCheckBox2.isSelected()){
           user.setgrad(2);}
             if(jCheckBox3.isSelected()){
           user.setgrad(3);}
              if(jCheckBox4.isSelected()){
           user.setgrad(4);} 
              if(jCheckBox2.isSelected() && jCheckBox3.isSelected() ){
           user.setgrad(23);}
              if(jCheckBox2.isSelected() && jCheckBox4.isSelected() ){
           user.setgrad(24);}
              if(jCheckBox4.isSelected() && jCheckBox3.isSelected() ){
           user.setgrad(34);}
           
           }
         

         if( db.FindUsername(user)==0 && !"".equals(jTextField1.getText()) && !"".equals(jTextField2.getText()) )
    {
        System.out.println("correct");
        db.AddUser(user);
        String sql ="select * from user";
        db.affichusers(sql ,jTable1);
        
        JOptionPane.showMessageDialog(null, "bien réussie");
    }else{    JOptionPane.showMessageDialog(null, "erreur, verifier les donnes username deja exist");}
    }catch(HeadlessException e){
    JOptionPane.showMessageDialog(null, "erreur, verifier les donnes");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int count = jTable1.getSelectedRow();
        String sql ="delete from user where grad !=\'1\' and id_user = '"+jTable1.getValueAt(count, 0)+"'"; 
        db.deletepointage(sql);
        sql ="select * from user";
        db.affichusers(sql ,jTable1);
    }//GEN-LAST:event_jButton2ActionPerformed
     ConnectDB db ;

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
          db = new ConnectDB();
        db.ConnexionIntoDataBase();
        
        String sql ="select * from user";
        db.affichusers(sql ,jTable1);
        
    }//GEN-LAST:event_formWindowActivated
    private void formWindowOpened(java.awt.event.WindowEvent evt) {  
      
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AjouteUser().setVisible(true);
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
