/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.des.produit;

import static gestion.des.produit.Login.vendeur;
import gestion.des.produit.dao.ConnectDB;
import gestion.des.produit.modele.User;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author ziram
 */
public class Main_frame extends javax.swing.JFrame {

   
   
    public Main_frame() {
       initComponents();
       showDate();
       showTime();
       setExtendedState(JFrame.MAXIMIZED_HORIZ);
       icon();
       setResizable(false);
       
       
    }
    void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("about.png")));
    }
     ConnectDB  db ;
     User user ;
    
    void permession(User user){
        int grad= db.FindGrad(user);
        switch (grad) {
            case 2:
                jLabel7.setVisible(false); //stock
                jLabel6.setVisible(false); //stock
                jLabel15.setVisible(false); //setting
                jLabel16.setVisible(false); //add user
                jLabel4.setVisible(false); //facture
                jLabel9.setVisible(false); // facture
                break;
            case 3:
                jLabel15.setVisible(false); //setting
                jLabel16.setVisible(false); //add user
                jLabel4.setVisible(false); //facture
                jLabel9.setVisible(false); // facture
                jLabel2.setVisible(false); // achat
                jLabel8.setVisible(false); // achat
                break;
            case 4:
                jLabel7.setVisible(false); //stock
                jLabel6.setVisible(false); //stock
                jLabel15.setVisible(false); //setting
                jLabel16.setVisible(false); //add user
                jLabel2.setVisible(false); // achat
                jLabel8.setVisible(false); // achat
                break;
            case 23:
                jLabel15.setVisible(false); //setting
                jLabel16.setVisible(false); //add user
                jLabel4.setVisible(false); //facture
                jLabel9.setVisible(false); // facture
                break;
            case 24:
                jLabel7.setVisible(false); //stock
                jLabel6.setVisible(false); //stock
                jLabel15.setVisible(false); //setting
                jLabel16.setVisible(false); //add user
                break;
            case 34:
                jLabel15.setVisible(false); //setting
                jLabel16.setVisible(false); //add user
                jLabel2.setVisible(false); // achat
                jLabel8.setVisible(false); // achat
                break;
            default:
                break;
        }
    } 
     
void showDate(){
    Date d=new Date();
    SimpleDateFormat sdf=new SimpleDateFormat("E dd-MM-YYYY");
    jLabel3.setText(sdf.format(d));
            
}
void showTime(){
    new Timer(0,new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            Date d=new Date();
             SimpleDateFormat sdf=new SimpleDateFormat("hh:mm:ss a");
    jLabel1.setText(sdf.format(d));
        }
    }).start();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Des Produits");
        setBackground(new java.awt.Color(255, 229, 247));
        setBounds(new java.awt.Rectangle(200, 120, 0, 0));
        setPreferredSize(new java.awt.Dimension(790, 630));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/nouveau.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16);
        jLabel16.setBounds(704, 219, 48, 50);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("h");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(317, 11, 228, 43);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/people-with-megaphone-and-social-media-marketing-icons.png"))); // NOI18N
        jLabel2.setToolTipText("tout concerné avec les achates");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(182, 36, 110)));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(288, 333, 180, 180);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(182, 36, 110));
        jLabel3.setText("u");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(612, 555, 166, 29);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(182, 36, 110));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Forn/Client");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 36, 110)));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(57, 519, 180, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/showing-tablet-s-blank-screen.png"))); // NOI18N
        jLabel10.setToolTipText("tout concerné avec les ventes");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(182, 36, 110)));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(288, 74, 180, 180);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(182, 36, 110));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Factures");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 36, 110)));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(518, 260, 180, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/people-holding-facebook-icon.png"))); // NOI18N
        jLabel5.setToolTipText("tout concerné avec les fornisseurs et les clients");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(182, 36, 110)));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(57, 333, 180, 180);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/MISe ajour.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(704, 128, 48, 50);

        jLabel17.setFont(new java.awt.Font("Tekton Pro", 1, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(182, 36, 110));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("username");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(618, 24, 160, 37);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/daffaires-monnaies-dolar-metal-argent-paiement-icone-3854-48.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18);
        jLabel18.setBounds(704, 313, 48, 50);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/businessapplications_information_briefcase_negoci_2317.png"))); // NOI18N
        jLabel13.setToolTipText("information sur l'application");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(704, 410, 48, 50);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(182, 36, 110));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Stock");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 36, 110)));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(57, 260, 180, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(182, 36, 110));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Achats");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 36, 110)));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(288, 519, 180, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/thumbs-up-monochrome-portrait-of-young-caucasian-blonde-woman-isolated-on-red-wall-beautiful-female-model-in-shirt-human-emotions-facial-expression-sales-ad-concept-youth-culture.png"))); // NOI18N
        jLabel7.setToolTipText("tout concerné avec le stock");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(182, 36, 110)));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(57, 72, 180, 182);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(182, 36, 110));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Ventes");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 36, 110)));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(288, 260, 180, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/caucasian-woman-s-portrait-isolated-on-blue-studio-background-in-neon-light-beautiful-female-model-with-red-hair-concept-of-human-emotions-facial-expression-sales-ad-bet-using-smartphone.png"))); // NOI18N
        jLabel4.setToolTipText("tout concerné avec les factures");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(182, 36, 110)));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(518, 72, 180, 182);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/2358046.png"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(182, 36, 110)));
        getContentPane().add(jLabel19);
        jLabel19.setBounds(31, 11, 206, 50);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/myriam-jessier-eveI7MOcSmw-unsplash.png"))); // NOI18N
        jLabel14.setToolTipText("tout concerné avec les achates");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(182, 36, 110)));
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14);
        jLabel14.setBounds(518, 333, 180, 180);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(182, 36, 110));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("DASHBOARD");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 36, 110)));
        getContentPane().add(jLabel20);
        jLabel20.setBounds(518, 519, 180, 30);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/about3.png"))); // NOI18N
        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(0, 0, 790, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     
        jLabel17.setText(vendeur);
        
        db = new ConnectDB();
        db.ConnexionIntoDataBase();
        
        user =new User();
        user.setnom_prenom_user(vendeur);

        permession(user);
    }//GEN-LAST:event_formWindowActivated

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Forniseur_Client fc=new Forniseur_Client();

        fc.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        StockForm sf=new StockForm();

        sf.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        VenteForm v=new VenteForm();v.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        AchatForm af=new AchatForm();

        af.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        FactureForm ff=new FactureForm();

        ff.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        BashoardForm b=new BashoardForm();

        b.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        AppInfo ap=new AppInfo();ap.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        VenteForm2 au=new VenteForm2();
        au.setVisible(true);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        AjouteUser au=new AjouteUser();au.setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        Setting au=new Setting();
        au.setVisible(true);
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
  
    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
