/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.des.produit;
import com.github.jinahya.imgscalr.Scalr;
import gestion.des.produit.dao.ConnectDB;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author ziram
 */
public class Setting extends javax.swing.JFrame {

    /**
     * Creates new form Setting
     */
    public Setting() {
        initComponents();
        db = new ConnectDB();
        db.ConnexionIntoDataBase();
        db. FindNomPrenomClient(jComboBox1); 
        db. FindNomPrenomClient(jComboBox2); 
        jTextField2.setText(db.NomeLocal());
        jTextField5.setText(db.Tel());
        jTextField6.setText(db.Addr());
        jTextField7.setText(db.TVA()+"");
        ImageIcon icon = new ImageIcon("logo.png");
        Image image = icon.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT);
        jLabel40.setIcon(icon);
        icon();
    }
    ConnectDB db;
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        vente = new javax.swing.JRadioButton();
        stock = new javax.swing.JRadioButton();
        client = new javax.swing.JRadioButton();
        fornisseur = new javax.swing.JRadioButton();
        facture = new javax.swing.JRadioButton();
        achat = new javax.swing.JRadioButton();
        pointage = new javax.swing.JRadioButton();
        ALL = new javax.swing.JRadioButton();

        setTitle("Setting");
        setBackground(new java.awt.Color(51, 102, 255));
        setIconImages(null);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(182, 36, 110));

        jLabel48.setBackground(new java.awt.Color(182, 36, 110));
        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("SETTING");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(240, 220, 243));
        jPanel6.setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATE", "VERSEMENT"
            }
        ));
        jTable2.setSelectionBackground(new java.awt.Color(182, 36, 110));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(10, 63, 172, 114);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("VERSMENT");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton1);
        jRadioButton1.setBounds(10, 38, 90, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("ABSSANCE");
        jPanel6.add(jRadioButton2);
        jRadioButton2.setBounds(105, 38, 90, 23);

        jPanel6.add(jComboBox1);
        jComboBox1.setBounds(10, 11, 172, 22);

        jPanel6.add(jComboBox2);
        jComboBox2.setBounds(10, 223, 172, 22);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATE", "CRIDIT"
            }
        ));
        jTable3.setSelectionBackground(new java.awt.Color(182, 36, 110));
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable3);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(10, 250, 172, 101);

        jButton5.setBackground(new java.awt.Color(182, 36, 110));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("AFFICHIE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5);
        jButton5.setBounds(10, 183, 122, 23);

        jLabel41.setText("TOTAL");
        jPanel6.add(jLabel41);
        jLabel41.setBounds(200, 163, 40, 14);

        jLabel42.setText("-");
        jPanel6.add(jLabel42);
        jLabel42.setBounds(250, 163, 119, 14);

        jLabel43.setText("TOTAL");
        jPanel6.add(jLabel43);
        jLabel43.setBounds(200, 337, 50, 14);

        jLabel44.setText("-");
        jPanel6.add(jLabel44);
        jLabel44.setBounds(250, 337, 119, 14);

        jButton6.setBackground(new java.awt.Color(182, 36, 110));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("AFFICHIE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6);
        jButton6.setBounds(188, 250, 181, 23);

        jButton8.setBackground(new java.awt.Color(182, 36, 110));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("NV ABSANCE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8);
        jButton8.setBounds(138, 183, 122, 23);

        jButton9.setBackground(new java.awt.Color(182, 36, 110));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("VIDE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9);
        jButton9.setBounds(188, 296, 181, 23);

        jButton10.setBackground(new java.awt.Color(182, 36, 110));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("VERSE");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10);
        jButton10.setBounds(285, 77, 84, 23);
        jPanel6.add(jTextField4);
        jTextField4.setBounds(200, 68, 79, 40);

        jButton11.setBackground(new java.awt.Color(182, 36, 110));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("VIDE");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton11);
        jButton11.setBounds(266, 183, 103, 23);
        jPanel6.add(jSeparator1);
        jSeparator1.setBounds(10, 212, 359, 10);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/about.png"))); // NOI18N
        jPanel6.add(jLabel4);
        jLabel4.setBounds(0, 0, 380, 370);

        jTabbedPane1.addTab("pointage", jPanel6);

        jPanel4.setBackground(new java.awt.Color(240, 223, 243));
        jPanel4.setLayout(null);

        jDateChooser3.setForeground(new java.awt.Color(204, 255, 255));
        jDateChooser3.setDateFormatString("yyyy-MM-dd ");
        jDateChooser3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel4.add(jDateChooser3);
        jDateChooser3.setBounds(47, 11, 142, 33);

        jLabel15.setText("From");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(10, 11, 40, 33);

        jLabel16.setText("To");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(197, 11, 30, 33);

        jDateChooser4.setForeground(new java.awt.Color(204, 255, 255));
        jDateChooser4.setDateFormatString("yyyy-MM-dd ");
        jDateChooser4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel4.add(jDateChooser4);
        jDateChooser4.setBounds(227, 11, 142, 33);

        jLabel17.setText("gain");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(10, 100, 40, 20);

        jLabel18.setText("entre");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(10, 130, 40, 20);

        jLabel19.setText("sorti");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(10, 160, 40, 20);

        jLabel20.setText("plus vent");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(10, 190, 60, 20);

        jLabel21.setText("moins vent");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(10, 230, 70, 20);
        jPanel4.add(jLabel22);
        jLabel22.setBounds(80, 100, 100, 20);
        jPanel4.add(jLabel23);
        jLabel23.setBounds(80, 130, 100, 20);
        jPanel4.add(jLabel24);
        jLabel24.setBounds(76, 162, 100, 20);
        jPanel4.add(jLabel25);
        jLabel25.setBounds(76, 192, 100, 20);
        jPanel4.add(jLabel26);
        jLabel26.setBounds(80, 230, 100, 20);

        jLabel27.setText("plus gain");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(10, 290, 60, 20);

        jLabel28.setText("moins gain");
        jPanel4.add(jLabel28);
        jLabel28.setBounds(10, 260, 70, 20);
        jPanel4.add(jLabel29);
        jLabel29.setBounds(80, 260, 90, 0);
        jPanel4.add(jLabel30);
        jLabel30.setBounds(80, 290, 90, 20);
        jPanel4.add(jLabel31);
        jLabel31.setBounds(180, 100, 100, 20);
        jPanel4.add(jLabel32);
        jLabel32.setBounds(180, 130, 100, 20);
        jPanel4.add(jLabel33);
        jLabel33.setBounds(180, 160, 100, 20);
        jPanel4.add(jLabel34);
        jLabel34.setBounds(180, 190, 100, 20);
        jPanel4.add(jLabel35);
        jLabel35.setBounds(180, 230, 80, 20);
        jPanel4.add(jLabel36);
        jLabel36.setBounds(170, 260, 60, 0);
        jPanel4.add(jLabel37);
        jLabel37.setBounds(170, 290, 60, 20);

        jButton4.setBackground(new java.awt.Color(182, 36, 110));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/001-technology.png"))); // NOI18N
        jButton4.setText("Calcule");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(241, 282, 128, 49);

        jLabel45.setText("plus rest");
        jPanel4.add(jLabel45);
        jLabel45.setBounds(10, 320, 60, 20);
        jPanel4.add(jLabel46);
        jLabel46.setBounds(80, 320, 90, 20);
        jPanel4.add(jLabel47);
        jLabel47.setBounds(170, 320, 60, 20);

        jButton12.setText("Plot");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);
        jButton12.setBounds(299, 50, 70, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/about.png"))); // NOI18N
        jPanel4.add(jLabel5);
        jLabel5.setBounds(-6, -6, 390, 370);

        jTabbedPane1.addTab("statistique", jPanel4);

        jPanel3.setBackground(new java.awt.Color(240, 224, 243));
        jPanel3.setLayout(null);

        jDateChooser1.setForeground(new java.awt.Color(204, 255, 255));
        jDateChooser1.setDateFormatString("yyyy-MM-dd ");
        jDateChooser1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel3.add(jDateChooser1);
        jDateChooser1.setBounds(43, 11, 142, 33);

        jDateChooser2.setForeground(new java.awt.Color(204, 255, 255));
        jDateChooser2.setDateFormatString("yyyy-MM-dd ");
        jDateChooser2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel3.add(jDateChooser2);
        jDateChooser2.setBounds(219, 11, 150, 33);

        jLabel7.setText("From");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 11, 30, 33);

        jLabel8.setText("To");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(189, 11, 30, 33);

        jLabel9.setText("Frais Toutal");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 76, 70, 14);

        jTextField1.setText("0.0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1);
        jTextField1.setBounds(78, 62, 107, 42);

        jLabel10.setText("gain :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 122, 60, 44);

        jLabel11.setText("0.0 DA");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(78, 122, 107, 44);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel3.add(jSpinner1);
        jSpinner1.setBounds(80, 190, 57, 30);

        jLabel12.setText("percentage :");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 184, 70, 40);

        jLabel13.setText("score :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 252, 70, 36);

        jLabel14.setText("0.0 DA");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(80, 263, 105, 14);

        jButton1.setBackground(new java.awt.Color(182, 36, 110));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/001-technology.png"))); // NOI18N
        jButton1.setText("Calcule");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(219, 294, 150, 49);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/about.png"))); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, 0, 380, 370);

        jTabbedPane1.addTab("ventair", jPanel3);

        jPanel5.setBackground(new java.awt.Color(240, 226, 244));
        jPanel5.setLayout(null);

        jLabel38.setText("Nome");
        jPanel5.add(jLabel38);
        jLabel38.setBounds(10, 20, 50, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField2);
        jTextField2.setBounds(70, 20, 108, 33);

        jLabel39.setText("Logo");
        jPanel5.add(jLabel39);
        jLabel39.setBounds(10, 144, 40, 20);

        jButton2.setBackground(new java.awt.Color(182, 36, 110));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("choose logo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(70, 140, 108, 23);

        jTextField3.setEditable(false);
        jPanel5.add(jTextField3);
        jTextField3.setBounds(180, 140, 188, 23);

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel40);
        jLabel40.setBounds(10, 164, 359, 187);

        jButton3.setBackground(new java.awt.Color(182, 36, 110));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(312, 27, 57, 23);

        jLabel1.setText("Tel");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(10, 50, 50, 30);
        jPanel5.add(jTextField5);
        jTextField5.setBounds(70, 50, 108, 30);

        jLabel2.setText("Address");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(10, 80, 50, 30);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField6);
        jTextField6.setBounds(70, 80, 108, 30);

        jLabel3.setText("TAX");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(10, 110, 40, 30);
        jPanel5.add(jTextField7);
        jTextField7.setBounds(70, 110, 48, 30);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/about.png"))); // NOI18N
        jPanel5.add(jLabel49);
        jLabel49.setBounds(0, 0, 380, 370);

        jTabbedPane1.addTab("Ticket", jPanel5);

        jPanel7.setBackground(new java.awt.Color(240, 232, 243));

        jButton7.setBackground(new java.awt.Color(182, 36, 110));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("VIDE TOUT LES TABLEAUX");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        buttonGroup2.add(vente);
        vente.setText("vente");

        buttonGroup2.add(stock);
        stock.setText("stock");

        buttonGroup2.add(client);
        client.setText("client");

        buttonGroup2.add(fornisseur);
        fornisseur.setText("fornisseur");

        buttonGroup2.add(facture);
        facture.setText("facture");

        buttonGroup2.add(achat);
        achat.setText("achat");

        buttonGroup2.add(pointage);
        pointage.setText("pointage");

        buttonGroup2.add(ALL);
        ALL.setText("ALL");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(client, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fornisseur, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                        .addGap(149, 149, 149)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pointage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ALL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(achat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(facture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vente)
                    .addComponent(facture))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stock)
                    .addComponent(achat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(client)
                    .addComponent(pointage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fornisseur)
                    .addComponent(ALL))
                .addGap(38, 38, 38)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("data", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                  
       
void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("Cartgrill_icon-icons.com_51191.png")));
    }
   
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
        String f = sdf.format(jDateChooser1.getDate());
        String t = sdf.format(jDateChooser2.getDate());
        String sql = "select * from vente where  date_vente between '"
                +f +" 00:00:00'and '"+t+" 23:59:59'";
        
        db.FindVentair(sql,jLabel11);
                float gain = Float.parseFloat(jLabel11.getText()) - Float.parseFloat(jTextField1.getText());
                jLabel11.setText(gain+" DA");
                int percentage = (int) jSpinner1.getValue();
                float hassila = gain*percentage/100 ; 
                jLabel14.setText(hassila+" DA");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser file =new JFileChooser();
        file.setFileFilter(new FileNameExtensionFilter("png images","png"));
        file.showSaveDialog(this);
        File f = file.getSelectedFile();
        String path = f.getAbsolutePath();
        jTextField3.setText(path);
        Image getAbsolutePath = null ;
        ImageIcon icon = new ImageIcon(path);
        Image image = icon.getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT);
        icon.setImage(image); 
        jLabel40.setIcon(icon);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            String sql="update info set name='"+jTextField2.getText()+"' ,tel='"+jTextField5.getText()+"' , addr ='"+jTextField6.getText()+"' , tva ='"+jTextField7.getText()+"'";
            if(!"".equals(jTextField3.getText())){
              saveImage();}
            if(!"".equals(jTextField2.getText())){
            db.savename(sql);}
        } catch (IOException ex) {
            Logger.getLogger(Setting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
        String f = sdf.format(jDateChooser3.getDate());
        String t = sdf.format(jDateChooser4.getDate());
        
        
        String sqlgain , sqlentre , sqlsorte , sqlpvent , sqlmvent , sqlpgain , sqlprest;
        
        
        sqlgain="select SUM(benefice) AS gain , COUNT(N_vente) AS qte from vente where  date_vente between '"
                +f +" 00:00:00'and '"+t+" 23:59:59'";
        sqlentre="select SUM(prix_a_payez) AS prix , COUNT(N_vente) AS qte from vente where  date_vente between '"
                +f +" 00:00:00'and '"+t+" 23:59:59'";
        sqlsorte="select SUM(prix_total) AS prix , SUM(quantite) AS qte from achat where  date_achat between '"
                +f +" 00:00:00'and '"+t+" 23:59:59'";
        sqlpvent="select MAX(qte_vente) AS max from stock ";
        sqlmvent="select MIN(qte_vente) AS min from stock  ";
        sqlpgain="select qte_vente , gain from stock";
        sqlprest="select MAX(qte_reste) AS max from stock ";
 
      
        
        db.Statistique(sqlgain , sqlentre , sqlsorte , sqlpvent , sqlmvent , sqlpgain , sqlprest , jLabel22 , jLabel23, jLabel24, jLabel25, jLabel26, jLabel27, jLabel28, jLabel29, jLabel30, jLabel31, jLabel32, jLabel33, jLabel34, jLabel35, jLabel36 , jLabel37, jLabel46, jLabel47);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         String sql ="Update vente set cridit= \'\' where nom_prenom_client= '"+jComboBox2.getSelectedItem()+"' ";
         if(JOptionPane.showConfirmDialog(null, "confirmer la supression de cridit de  '"+jComboBox2.getSelectedItem()+"' ? ", "suppression"
            ,JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
         db.ajouteversmentouab(sql);
         }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String sql="select dateversement , prix from pointage where nom= '"+jComboBox1.getSelectedItem()+"'";
        String sql2="select dateabsonce from pointage where nom= '"+jComboBox1.getSelectedItem()+"'";
        if(jRadioButton1.isSelected()){
          db.pointage(sql , jTable2 , 1 , jLabel42);
          
        }else { db.pointage(sql2 , jTable2 , 2 , jLabel42);} 

        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
        String sql ="delete from pointage where nom= '"+jComboBox1.getSelectedItem()+"' and dateversement IS NULL ";
        String sql2 ="delete from pointage where nom= '"+jComboBox1.getSelectedItem()+"' and dateabsonce IS NULL ";
       if(JOptionPane.showConfirmDialog(null, "confirmer la supression ?", "suppression"
            ,JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
        if(jRadioButton1.isSelected()){
          db.deletepointage(sql2);
          
        }else { db.deletepointage(sql);}
       } 
      
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "confirmer l absance de '"+jComboBox1.getSelectedItem()+"' ", "absant"
            ,JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
        String sql ="INSERT INTO pointage(nom , dateabsonce) VALUES('"+jComboBox1.getSelectedItem()+"' , '"+db.showDate()+"')";
         
         db.ajouteversmentouab(sql);  
         
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         if(JOptionPane.showConfirmDialog(null, "confirmer le versment de '"+jTextField4.getText()+"' --> '"+jComboBox1.getSelectedItem()+"' ", "verse"
            ,JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
        String sql ="INSERT INTO pointage(nom , dateversement , prix) VALUES('"+jComboBox1.getSelectedItem()+"' , '"+db.showDate()+"' , '"+jTextField4.getText()+"')";
         
         db.ajouteversmentouab(sql);  
         
        }
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String sql="select date_vente , cridit from vente where nom_prenom_client= '"+jComboBox2.getSelectedItem()+"'";
        db.affichecridit(sql , jTable3 , jLabel44);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         if(ALL.isSelected()){
            if (JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer tout les tableaux  ?", "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
              { 
              db.clear("stock");
              db.clear("achat");
              db.clear("client");
              db.clear("facture");
              db.clear("vente");
              db.clear("fornisseur");
              db.clear("pointage");
              }
         }else if(stock.isSelected()){
              if (JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer tout le tableau de stock  ?", "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
              { db.clear("stock");
              
         }
         }else if(vente.isSelected()){
              if (JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer tout le tableau de vente  ?", "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
              { db.clear("vente");
              
         }
         }else if(client.isSelected()){
              if (JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer tout le tableau de client  ?", "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
              { db.clear("client");
              
         }
         }else if(achat.isSelected()){
              if (JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer tout le tableau de achat  ?", "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
              { db.clear("achat");
              
         }
         }else if(facture.isSelected()){
              if (JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer tout le tableau de facture  ?", "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
              { db.clear("facture");
              
         }
         }else if(fornisseur.isSelected()){
              if (JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer tout le tableau de fornisseur  ?", "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
              { db.clear("fornisseur");
              
         }
         }else if(pointage.isSelected()){
              if (JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer tout le tableau de pointage  ?", "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
              { db.clear("pointage");
              
         }
         }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    
    
    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
               try{
           
        
          String url = "jdbc:sqlite:gestion_de_produit.db";      
          Connection cnx =  DriverManager.getConnection(url);
       
           SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd"); 
           String sql ="select date_vente , SUM(benefice) as gain from vente  group by date_vente";
        if( !(jDateChooser3.getDate() == null || jDateChooser4.getDate() == null) ){
            sql ="select date_vente , SUM(benefice) as gain from vente  where date_vente between'" + sdf.format(jDateChooser3.getDate())  +" ' and '"+ sdf.format(jDateChooser4.getDate()) + "' group by date_vente";

           }
       
        JDBCCategoryDataset dataset = new JDBCCategoryDataset( cnx , sql) ;
       
        JFreeChart chart =ChartFactory.createLineChart("Statistique", "Date", "Gain", dataset, PlotOrientation.VERTICAL, false, true, true) ;
        BarRenderer ren = null ;
        CategoryPlot  plot = null ;
        ren = new BarRenderer();
        ChartFrame f = new ChartFrame("Statistique" , chart);
        f.setVisible(true);
        f.setSize(700 , 400);
      
   
        
        
       }catch(SQLException e){}
        
        
        
    }//GEN-LAST:event_jButton12ActionPerformed
    private void saveImage() throws IOException{
    File fl = new File(jTextField3.getText());    
    BufferedImage readed = ImageIO.read(fl);
    
    File f =new File("logo.png");
        

    ImageIO.write(Scalr.resize(readed,100), "png",f );
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ALL;
    private javax.swing.JRadioButton achat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton client;
    private javax.swing.JRadioButton facture;
    private javax.swing.JRadioButton fornisseur;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JRadioButton pointage;
    private javax.swing.JRadioButton stock;
    private javax.swing.JRadioButton vente;
    // End of variables declaration//GEN-END:variables

   
}
