/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.des.produit;

//import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
//import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.time;
import static gestion.des.produit.Login.vendeur;
import gestion.des.produit.dao.ConnectDB;
import gestion.des.produit.modele.Vente;
import java.awt.HeadlessException;

import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.text.SimpleDateFormat;

import java.util.ArrayList;
import java.util.Base64;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import static org.apache.commons.codec.binary.Base64.encodeBase64;


/**
 *
 * @author ziram
 */
public final class VenteForm2 extends javax.swing.JFrame {

    /**
     * Creates new form VenteForm
     */
    private float tva ;
    public VenteForm2() {
        initComponents();icon();
        
    }
    void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("Cartgrill_icon-icons.com_51191.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField6 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setTitle("vente");
        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(1600, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 36, 110)));
        jPanel1.setLayout(null);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N prod", "Designation", "Qte T", "Qte V", "Qte R", "Prix V", "Gain", "prix grant"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(2);
        jTable1.setSelectionBackground(new java.awt.Color(182, 36, 110));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(11, 87, 600, 490);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/viewmag--icone-5948-32.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 50, 40, 30);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(160, 50, 160, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/exchange.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(370, 50, 40, 30);

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nbre", "designation", "prix", "qauntité"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(20);
        jTable2.setSelectionBackground(new java.awt.Color(254, 255, 185));
        jTable2.setSelectionForeground(new java.awt.Color(0, 153, 102));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(90);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(620, 94, 510, 200);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/index-up-upload-icone-7700-32.png"))); // NOI18N
        jButton3.setText("ajouter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(740, 300, 143, 41);

        jTable3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gain", "Qte"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setRowHeight(20);
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable3.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(1140, 94, 140, 200);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jLabel5.setText("Qte :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(620, 300, 36, 40);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(5, 132, 58));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(660, 350, 78, 40);

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/supprimer.png"))); // NOI18N
        jButton5.setText("supprimer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(740, 350, 143, 41);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(182, 36, 110));
        jLabel6.setText("PT:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(620, 10, 60, 80);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 153, 0));
        jLabel9.setText("0.0");
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(958, 653, 0, 29);

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/imprimer-icone-8818-48.png"))); // NOI18N
        jButton6.setText("imprimer ticket");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(890, 350, 230, 40);

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/daffaires-monnaies-dolar-metal-argent-paiement-icone-3854-48.png"))); // NOI18N
        jButton7.setText("prix totale");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(620, 510, 230, 60);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "inconnus" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(690, 410, 159, 28);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel10.setText("Client  :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(620, 410, 64, 24);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(690, 450, 159, 28);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel11.setText("Remise:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(620, 450, 65, 24);

        jButton13.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/suppp.png"))); // NOI18N
        jButton13.setText("Supprimer ticket");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(890, 300, 230, 41);
        jButton13.getAccessibleContext().setAccessibleDescription("");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel18.setText("Cridit  :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(620, 480, 65, 24);

        jTextField10.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jPanel1.add(jTextField10);
        jTextField10.setBounds(690, 480, 159, 28);

        jCheckBox1.setText("en grant");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(10, 60, 67, 23);

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(140, 10, 350, 20);

        jSpinner1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        jPanel1.add(jSpinner1);
        jSpinner1.setBounds(660, 300, 78, 40);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setFont(new java.awt.Font("Imprint MT Shadow", 0, 48)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 255, 0));
        jTextField3.setText("0.0");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(680, 10, 600, 79);

        jLabel7.setText("-");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(540, 580, 70, 14);

        jLabel8.setText("TOTAL :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1140, 300, 50, 20);

        jLabel12.setText("-");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(1190, 300, 110, 20);

        jLabel3.setText("Code bar :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 10, 60, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/about3.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1440, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1367, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 ConnectDB db;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      db=new ConnectDB();db.ConnexionIntoDataBase();db.AllStockVente(jTable1);
      DESIGNATION=new ArrayList<>();
      PRIX=new ArrayList<>();
      QTE=new ArrayList<>();
      GAIN=new ArrayList<>();
       db.FindNomPrenomClient(jComboBox1);
      
      jTextField6.requestFocusInWindow();
   
              
    }//GEN-LAST:event_formWindowOpened
int count;
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     
    }//GEN-LAST:event_formWindowActivated

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        // TODO add your handling code here:
        if(jTextField6.getText().length()==13){
            db.AllStockVenteRcherchebc(jTable1, jTextField6.getText());
            jTextField6.selectAll();
           // jTextField2.setText(jTable1.getValueAt(0, 0) + "");

            if(jCheckBox1.isSelected()){
                fillTable(jTable1.getValueAt(0, 1)+"",Float.parseFloat(jTable1. getValueAt(0, 7)+""),
                    Integer.parseInt( jSpinner1.getValue().toString()),(Float.parseFloat(jTable1. getValueAt(0, 5 )+"")-Float.parseFloat(jTable1. getValueAt(0, 7)+"")),
                    jTable2, jTable3);}
            else{fillTable(jTable1.getValueAt(0, 1)+"",Float.parseFloat(jTable1. getValueAt(0, 5)+""),
                Integer.parseInt( jSpinner1.getValue().toString()),Float.parseFloat(jTable1. getValueAt(0, 6)+""),
                jTable2, jTable3);}
        db.UpdateQteResteMinus((int) jTable1.getValueAt(0, 0),Integer.parseInt(jSpinner1.getValue().toString()));
        db.AllStockVente(jTable1);
        FillArray(jTable2, jTable3, jTextField3, jLabel9, jTextField5.getText());
        jTextField6.setText("");
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        FillArray(jTable2, jTable3, jTextField3, jLabel9, jTextField5.getText());
        jLabel7.setText(""+tva);
        String remise=jTextField5.getText();
        if("".equals(remise)){remise="0.0";}
        float total =Float.parseFloat(jTextField3.getText())+Float.parseFloat(remise)-Float.parseFloat(jLabel7.getText()); 
        jLabel12.setText(total+" DA");
    }//GEN-LAST:event_jButton7ActionPerformed
    
    private static String encodeFileToBase64Binary(File file) throws Exception{
            FileInputStream fileInputStreamReader = new FileInputStream(file);
            byte[] bytes = new byte[(int)file.length()];
            fileInputStreamReader.read(bytes);
            return new String(encodeBase64(bytes), "UTF-8");
        }
       String encodstring= "logo";

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
             
       
            marchendise="";int temp=0;
            float somePrix=0;
            float someGain=0;
            
            for(int i=0;i<jTable2.getRowCount();i++){
                DESIGNATION.add((String)jTable2.getValueAt(i, 1));
                QTE.add((int)jTable2.getValueAt(i, 3));
                PRIX.add((float)jTable2.getValueAt(i, 2));
                somePrix=QTE.get(i)*PRIX.get(i)+somePrix;
                temp=temp+1;
                marchendise=marchendise+"N° "+temp+" DES : "+DESIGNATION.get(i)+" prix : "+PRIX.get(i)
                        +" qte : "+QTE.get(i)+ "\n"    ;
            }
                 SimpleDateFormat sdft = new SimpleDateFormat("YYYY/MM/dd HH:mm:ss"); 
            SimpleDateFormat sdf = new SimpleDateFormat("YYYY/MM/dd"); 
            Date d = new Date();
           Impression imprim = new Impression( db.NomeLocal(),encodstring, vendeur+" ", "00x xxxxxxx", jTextField3.getText()+" DA", sdft.format(d),marchendise, jTextField5.getText()+" DA",jLabel7.getText() + " DA", jLabel12.getText(), db.Tel(),db.Addr() );
           imprim.actionPerformed(evt);
          
        } catch (Exception ex) {
            Logger.getLogger(VenteForm2.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{
            //--------------------------------------------------------
            db.UpdateQteResteAdd(DESIGNATION.get(Integer.parseInt(jTextField4.getText())),
                QTE.get(Integer.parseInt(jTextField4.getText()))     );
            db.AllStockVente(jTable1);
            //-------------------------------------------------------------
            DESIGNATION.remove(Integer.parseInt(jTextField4.getText()));
            PRIX.remove(Integer.parseInt(jTextField4.getText()));
            QTE.remove(Integer.parseInt(jTextField4.getText()));
            GAIN.remove(Integer.parseInt(jTextField4.getText()));
            Object  row1[] = new Object[4];
            Object  row2[] = new Object[2];
            mo1.setRowCount(0);
            mo2.setRowCount(0);
            ii=DESIGNATION.size()+1;int r=1;
            for(int i=0;i<DESIGNATION.size();i++){
                row1[0]=  r++;
                row1[1]= DESIGNATION.get(i);
                row1[2]= PRIX.get(i);
                row1[3]= QTE.get(i);
                row2[0]=GAIN.get(i);
                row2[1]=QTE.get(i);
                mo1.addRow(row1);
                mo2.addRow(row2);
            }

            jTextField4.setText("");
            FillArray(jTable2, jTable3, jTextField3, jLabel9, jTextField5.getText());
             jLabel7.setText(""+tva);
        String remise=jTextField5.getText();
        if("".equals(remise)){remise="0.0";}
        float total =Float.parseFloat(jTextField3.getText())+Float.parseFloat(remise)-Float.parseFloat(jLabel7.getText()); 
        jLabel12.setText(total+" DA");

        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "ereur operation"," ereur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{       if(jCheckBox1.isSelected()){
            fillTable(jTable1.getValueAt(count, 1)+"",Float.parseFloat(jTable1. getValueAt(count, 7)+""),
                Integer.parseInt( jSpinner1.getValue().toString()),(Float.parseFloat(jTable1. getValueAt(count, 5 )+"")-Float.parseFloat(jTable1. getValueAt(count, 7)+"")),
                jTable2, jTable3);}
        else{fillTable(jTable1.getValueAt(count, 1)+"",Float.parseFloat(jTable1. getValueAt(count, 5)+""),
            Integer.parseInt( jSpinner1.getValue().toString()),Float.parseFloat(jTable1. getValueAt(count, 6)+""),
            jTable2, jTable3);}
    db.UpdateQteResteMinus((int) jTable1.getValueAt(count, 0),Integer.parseInt(jSpinner1.getValue().toString()));
    db.AllStockVente(jTable1);
    FillArray(jTable2, jTable3, jTextField3, jLabel9, jTextField5.getText());
     jLabel7.setText(""+tva);
        String remise=jTextField5.getText();
        if("".equals(remise)){remise="0.0";}
        float total =Float.parseFloat(jTextField3.getText())+Float.parseFloat(remise)-Float.parseFloat(jLabel7.getText()); 
        jLabel12.setText(total+" DA");

    }
    catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null, "ereur operation"," ereur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        jTextField4.setText(jTable2.getSelectedRow()+"");
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        db.AllStockVente(jTable1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:

        if("".equals(jTextField1.getText())){
            db.AllStockVente(jTable1);
        }else{
            db.AllStockVenteRcherche(jTable1, jTextField1.getText());}
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        db.AllStockVenteRcherche(jTable1, jTextField1.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        count = jTable1.getSelectedRow();
      //  jTextField2.setText(jTable1.getValueAt(count, 0) + "");
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try{ if (JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer tout le tableau de ticket ?", "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
{
     Vente v=new Vente(0, jComboBox1.getSelectedItem()+"", jTextField5.getText(), marchendise, Float.parseFloat(jTextField3.getText())
     ,Float.parseFloat(jLabel9.getText())  ,db.showDateTime()+"" ,vendeur  ,jTextField10.getText()  );
     db.insertVente(v);
    
       mo1.setRowCount(0);
       mo2.setRowCount(0);
       ii=1;
       DESIGNATION.clear();
       PRIX.clear();
       QTE.clear();
       GAIN.clear();
       jTextField4.setText("");
       jTextField3.setText("0.0");
       jLabel9.setText("0.0");
}
}catch(HeadlessException e){
     JOptionPane.showMessageDialog(null, 
             "ereur operation"," ereur", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton13ActionPerformed
int I;String marchendise;
    void FillArray (JTable T,JTable T2,JTextField j1,JLabel j2 ,String f){
    DESIGNATION.clear();QTE.clear();PRIX.clear();GAIN.clear();
    marchendise="";int temp=0;
            float somePrix=0;
             float someGain=0;
             if("".equals(f)){f="0";}
    for(int i=0;i<T.getRowCount();i++){
        DESIGNATION.add((String)T.getValueAt(i, 1));
        QTE.add((int)T.getValueAt(i, 3));
        PRIX.add((float)T.getValueAt(i, 2));
        GAIN.add((float)T2.getValueAt(i, 0));
        somePrix=QTE.get(i)*PRIX.get(i)+somePrix;
        someGain=QTE.get(i)*GAIN.get(i)+someGain;
        temp=temp+1;
          marchendise=marchendise+"N° "+temp+" DES : "+DESIGNATION.get(i)+" pr : "+PRIX.get(i)
              +" qte : "+QTE.get(i)+ "\n"    ;    
    }
    tva = db.TVA()*(somePrix - Float.parseFloat(f))/100;
    j1.setText((somePrix - Float.parseFloat(f) + tva)+"");
    j2.setText((someGain - Float.parseFloat(f)+tva)+"");
}
DefaultTableModel mo1;
DefaultTableModel mo2;
    int ii=1;
    ArrayList<String> DESIGNATION;
    ArrayList<Float> PRIX;
    ArrayList<Integer> QTE;
    ArrayList<Float> GAIN;
    void fillTable(String des,float prix,int qte,float gain,JTable t1,JTable t2){
     mo1 = (DefaultTableModel) t1.getModel();
     mo2 = (DefaultTableModel) t2.getModel();
               Object  row1[] = new Object[4];
               Object  row2[] = new Object[2];
                DESIGNATION.add(des);
                PRIX.add(prix);
                QTE.add(qte);
                GAIN.add(gain);
             //  for(int i=0;i<DESIGNATION.size();i++){
         row1[0]=   ii++;  
         row1[1]= des;
         row1[2]= prix;
         row1[3]= qte;
         row2[0]=gain;
         row2[1]=qte;
         mo1.addRow(row1);
         mo2.addRow(row2);  
           //     }
         
         
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenteForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenteForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenteForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenteForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenteForm2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
