/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.des.produit;

//import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
//import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.time;
import static gestion.des.produit.Login.vendeur;
import gestion.des.produit.dao.ConnectDB;
import gestion.des.produit.modele.Vente;
import java.awt.HeadlessException;

import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import static org.apache.commons.codec.binary.Base64.encodeBase64;

/**
 *
 * @author ziram
 */
public final class VenteForm extends javax.swing.JFrame {

    /**
     * Creates new form VenteForm
     */
    private float tva ;
    public VenteForm() {
        initComponents();icon();
    }
    void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("Cartgrill_icon-icons.com_51191.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField11 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jButton14 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jDateChooser5 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setTitle("vente");
        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(1346, 740));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 36, 110)));
        jPanel1.setLayout(null);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N prod", "Designation", "Qte T", "Qte V", "Qte R", "Prix V", "Gain", "prix_grant"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(2);
        jTable1.setSelectionBackground(new java.awt.Color(182, 36, 110));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(90);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(15, 66, 573, 175);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/viewmag--icone-5948-32.png"))); // NOI18N
        jButton1.setText("recherche");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(304, 251, 141, 39);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(114, 255, 180, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jLabel1.setText("Designaation");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(15, 259, 95, 22);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/exchange.png"))); // NOI18N
        jButton2.setText("actualiser");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(451, 251, 137, 39);

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nbre", "designation", "prix", "qauntité"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(20);
        jTable2.setSelectionBackground(new java.awt.Color(254, 255, 185));
        jTable2.setSelectionForeground(new java.awt.Color(0, 153, 102));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(594, 67, 413, 174);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/index-up-upload-icone-7700-32.png"))); // NOI18N
        jButton3.setText("ajouter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(779, 247, 150, 50);

        jTable3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gain", "Qte"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setRowHeight(20);
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(1016, 67, 138, 174);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jLabel4.setText("ticket :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(680, 22, 49, 23);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jLabel5.setText("Qte :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(655, 261, 36, 22);

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/suppp.png"))); // NOI18N
        jButton4.setText("Supprimer tout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(733, 12, 197, 43);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(5, 132, 58));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(695, 309, 78, 35);

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/supprimer.png"))); // NOI18N
        jButton5.setText("supprimer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(779, 303, 150, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(182, 36, 110));
        jLabel6.setText("pt :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(312, 297, 67, 39);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 153, 0));
        jLabel7.setText("gain :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(312, 342, 67, 48);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(182, 36, 110));
        jLabel8.setText("0.0");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(392, 297, 275, 39);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 153, 0));
        jLabel9.setText("0.0");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(397, 342, 270, 48);

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/imprimer-icone-8818-48.png"))); // NOI18N
        jButton6.setText("imprimer ticket");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(99, 342, 195, 48);

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/daffaires-monnaies-dolar-metal-argent-paiement-icone-3854-48.png"))); // NOI18N
        jButton7.setText("prix totale");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(99, 297, 195, 44);

        jTable5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N vente", "nom prenom cl", "cridit", "remise", "marchendise", "prix a payez", "bénéfice", "date vente", "vendeur"
            }
        ));
        jTable5.setRowHeight(40);
        jTable5.setRowMargin(2);
        jTable5.setSelectionBackground(new java.awt.Color(182, 36, 110));
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable5);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(344, 435, 810, 182);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "inconnus" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(84, 435, 159, 28);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/viewmag--icone-5948-32.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(160, 538, 46, 41);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel10.setText("Client  :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(15, 437, 65, 24);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(84, 469, 159, 28);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel11.setText("Remise:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(15, 471, 65, 24);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jPanel1.add(jTextField6);
        jTextField6.setBounds(15, 585, 139, 28);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nom prenom", "nom vendeur", "date" }));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(15, 546, 139, 27);

        jButton9.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/MISe ajour.png"))); // NOI18N
        jButton9.setText("modifier");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(538, 623, 150, 40);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/imprimer-icone-3918-48.png"))); // NOI18N
        jButton10.setText("imprimer");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(1160, 527, 150, 40);

        jButton11.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/detaile.png"))); // NOI18N
        jButton11.setText("detaille");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(1009, 385, 145, 44);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(0, 51, 255));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(951, 392, 40, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        jLabel12.setText("Vente :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(620, 400, 60, 30);

        jButton12.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/supprimer.png"))); // NOI18N
        jButton12.setText("supprimer");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(698, 623, 150, 40);

        jButton13.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/Save_icon-icons.com_73702.png"))); // NOI18N
        jButton13.setText("enregistrer");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(378, 623, 150, 40);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jLabel13.setText("au :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(162, 613, 26, 22);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jLabel14.setText("du :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(160, 579, 28, 22);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText(".");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(11, 669, 315, 25);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText(".");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(332, 669, 315, 25);

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jTextField9);
        jTextField9.setBounds(710, 400, 55, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        jLabel17.setText("id ");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(690, 400, 21, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel18.setText("Cridit  :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(17, 505, 63, 24);

        jTextField10.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jPanel1.add(jTextField10);
        jTextField10.setBounds(84, 503, 159, 29);

        jCheckBox1.setText("en grant");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(11, 43, 67, 23);

        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setDoubleBuffered(true);
        jTextField11.setFocusCycleRoot(true);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField11);
        jTextField11.setBounds(246, 25, 179, 20);

        jSpinner1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        jSpinner1.setToolTipText("");
        jSpinner1.setBorder(null);
        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jSpinner1);
        jSpinner1.setBounds(695, 257, 78, 34);

        jButton14.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(204, 0, 0));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/annuler-icone-6802-48.png"))); // NOI18N
        jButton14.setText("vider");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(1160, 577, 150, 40);

        jLabel19.setText("-");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(15, 297, 45, 14);

        jLabel20.setText("TOTAL :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(1003, 247, 50, 14);

        jLabel21.setText("-");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(1059, 247, 90, 14);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/simulateur-argent-icone-5481-48.png"))); // NOI18N
        jButton15.setText("Exporte");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(1160, 435, 150, 40);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/icon/index-up-upload-icone-7700-32.png"))); // NOI18N
        jButton16.setText("Importe");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(1160, 481, 150, 40);

        jDateChooser4.setForeground(new java.awt.Color(204, 255, 255));
        jDateChooser4.setDateFormatString("yyyy-MM-dd ");
        jDateChooser4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.add(jDateChooser4);
        jDateChooser4.setBounds(192, 613, 142, 28);

        jDateChooser5.setForeground(new java.awt.Color(204, 255, 255));
        jDateChooser5.setDateFormatString("yyyy-MM-dd ");
        jDateChooser5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.add(jDateChooser5);
        jDateChooser5.setBounds(192, 579, 142, 28);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/des/produit/about3.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1352, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 ConnectDB db;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      db=new ConnectDB();db.ConnexionIntoDataBase();db.AllStockVente(jTable1);
      DESIGNATION=new ArrayList<>();
      PRIX=new ArrayList<>();
      QTE=new ArrayList<>();
      GAIN=new ArrayList<>();
       db.FindNomPrenomClient(jComboBox1);
      db.AllVente(jTable5);
      jLabel13.setVisible(false); jLabel14.setVisible(false);
      jDateChooser4.setVisible(false);
      jDateChooser5.setVisible(false);
      jTextField11.requestFocusInWindow();
  
              
    }//GEN-LAST:event_formWindowOpened
int count;
    
    private static String encodeFileToBase64Binary(File file) throws Exception{
            FileInputStream fileInputStreamReader = new FileInputStream(file);
            byte[] bytes = new byte[(int)file.length()];
            fileInputStreamReader.read(bytes);
            return new String(encodeBase64(bytes), "UTF-8");
        }
          String encodstring= "logo";

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     
    }//GEN-LAST:event_formWindowActivated

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            JFileChooser file =new JFileChooser();
            file.setFileFilter(new FileNameExtensionFilter("csv file","csv"));
            file.showSaveDialog(this);
            File f = file.getSelectedFile();
            String path = f.getAbsolutePath();
            BufferedReader reader = new BufferedReader(new FileReader(path));

            while( reader.readLine() !=null){
                db.importevente(reader.readLine());
            }
            JOptionPane.showMessageDialog(null, "Operation Done"," Done",
                JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException ex) {
            Logger.getLogger(AchatForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try {
            // TODO add your handling code here:
            ExcelExporter ex =new ExcelExporter();
            File f =  new File("ventes.xls");
            try (FileWriter fw = new FileWriter("ventes.csv")) {
                String sql="select * from vente";
                db.csvvente(sql , fw);
                fw.flush();
            }
            ex.exportTable(jTable5, f);
            JOptionPane.showMessageDialog(null, "operation Done"," Done",
                JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException ex1) {
            Logger.getLogger(VenteForm.class.getName()).log(Level.SEVERE, null, ex1);
        }

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer tout le tableau de Vente ?", "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
        { db.clear("vente");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped

        if(jTextField11.getText().length()==13){
            db.AllStockVenteRcherchebc(jTable1, jTextField11.getText());
            jTextField11.selectAll();

            if(jCheckBox1.isSelected()){
                fillTable(jTable1.getValueAt(0, 1)+"",Float.parseFloat(jTable1. getValueAt(0, 7)+""),
                    Integer.parseInt( jSpinner1.getValue().toString()),(Float.parseFloat(jTable1. getValueAt(0, 5 )+"")-Float.parseFloat(jTable1. getValueAt(0, 7)+"")),
                    jTable2, jTable3);}
            else{fillTable(jTable1.getValueAt(0, 1)+"",Float.parseFloat(jTable1. getValueAt(0, 5)+""),
                Integer.parseInt( jSpinner1.getValue().toString()),Float.parseFloat(jTable1. getValueAt(0, 6)+""),
                jTable2, jTable3);}
        db.UpdateQteResteMinus((int) jTable1.getValueAt(0, 0),Integer.parseInt(jSpinner1.getValue().toString()));
        db.AllStockVente(jTable1);
        FillArray(jTable2, jTable3, jLabel8, jLabel9, jTextField5.getText());
        jTextField11.setText("");
        }
    }//GEN-LAST:event_jTextField11KeyTyped

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try{
            Vente v=new Vente(0, jComboBox1.getSelectedItem()+"", jTextField5.getText(), marchendise, Float.parseFloat(jLabel8.getText())
                ,Float.parseFloat(jLabel9.getText())  ,db.showDateTime()+"" ,vendeur  ,jTextField10.getText()  );
            db.insertVente(v);
            db.AllVente(jTable5);
            JOptionPane.showMessageDialog(null, " MERCIE <3");
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "ereur operation"," ereur",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(null, "confirmer la supression ?",
                "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
        {
            db.DeleteVente(Integer.parseInt(jTextField9.getText()));
            db.AllVente(jTable5);}

        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ereur operation"," ereur",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        DetailleVenteForm D=new DetailleVenteForm();
        D.jTextFieldID.setText(jTable5.getValueAt(I, 0)+"");
        D.jTextFieldNOM_PRE.setText(jTable5.getValueAt(I, 8)+"");
        D.jTextFieldCOmm.setText(jTable5.getValueAt(I, 3)+"");
        D.jTextFieldPrix.setText(jTable5.getValueAt(I, 5)+"");
        D.jTextFieldBEni.setText(jTable5.getValueAt(I, 6)+"");
        D.jTextFieldDATE.setText(jTable5.getValueAt(I, 7)+"");
        D.jTextAreaMAR.setText(jTable5.getValueAt(I, 4)+"");
        D.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        MessageFormat Header = new MessageFormat("vente"
            + " " + db.showDateTime() + "");

        MessageFormat footer = new MessageFormat("page{0,number,integer}");
        try {

            jTable5.print(JTable.PrintMode.FIT_WIDTH, Header, footer);

        } catch (java.awt.print.PrinterException ex) {
            System.err.format("ereur dimpression", ex.getMessage());
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try{
            db.UpdatVente(Integer.parseInt(jTextField9.getText()),
                jComboBox1.getSelectedItem()+"", jTextField5.getText(), jTextField10.getText());
            db.AllVente(jTable5);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "ereur operation"," ereur",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if(jComboBox2.getSelectedItem().equals("date")){
            jLabel13.setVisible(true); jLabel14.setVisible(true);
            jDateChooser4.setVisible(true);
            jDateChooser5.setVisible(true);}
        else /*(jComboBox2.getSelectedItem().equals("nom prenom"))*/{
            jLabel13.setVisible(false); jLabel14.setVisible(false);
            jDateChooser4.setVisible(false);
            jDateChooser5.setVisible(false);
            jLabel15.setText("");jLabel16.setText("");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked

    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try { String sql;
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
            if(jComboBox2.getSelectedItem().equals("nom prenom")){
                sql="select * from vente where nom_prenom_client like '"
                +jTextField6.getText()+"%'" ;
                db.FindVente(jTable5, sql,jLabel15,jLabel16);
            }else if(jComboBox2.getSelectedItem().equals("date")){
                sql="select * from vente where  date_vente between '"
                +sdf.format(jDateChooser5.getDate()) +" 00:00:00'and '"+sdf.format(jDateChooser4.getDate())+" 23:59:59'";
                db.FindVente(jTable5, sql,jLabel15,jLabel16);

            }else if(jComboBox2.getSelectedItem().equals("nom vendeur")){
                sql="select * from vente where vendeur like '"
                +jTextField6.getText()+"%'" ;
                db.FindVente(jTable5, sql,jLabel15,jLabel16);
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        try {
            I=jTable5.getSelectedRow();
            jTextField7.setText(I+"");
            jTextField9.setText(jTable5.getValueAt(I, 0)+"");
            jTextField5.setText(jTable5.getValueAt(I, 3)+"");
            jTextField10.setText(jTable5.getValueAt(I, 2)+"");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ereur operation"," ereur",
                JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jTable5MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        FillArray(jTable2, jTable3, jLabel8, jLabel9, jTextField5.getText());
        jLabel19.setText(""+tva);
        String remise=jTextField5.getText();
        if("".equals(remise)){remise="0.0";}
        float total =Float.parseFloat(jLabel8.getText())+Float.parseFloat(remise)-Float.parseFloat(jLabel19.getText());
        jLabel21.setText(total+" DA");

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {

            marchendise="";int temp=0;
            float somePrix=0;
            float someGain=0;

            for(int i=0;i<jTable2.getRowCount();i++){
                DESIGNATION.add((String)jTable2.getValueAt(i, 1));
                QTE.add((int)jTable2.getValueAt(i, 3));
                PRIX.add((float)jTable2.getValueAt(i, 2));
                somePrix=QTE.get(i)*PRIX.get(i)+somePrix;
                temp=temp+1;
                marchendise=marchendise+"N° "+temp+" DES : "+DESIGNATION.get(i)+" prix : "+PRIX.get(i)
                +" qte : "+QTE.get(i)+ "\n"    ;
            }
            SimpleDateFormat sdft = new SimpleDateFormat("YYYY/MM/dd HH:mm:ss"); 
            SimpleDateFormat sdf = new SimpleDateFormat("YYYY/MM/dd"); 
            Date d = new Date();
            Impression imprim = new Impression(db.NomeLocal(),encodstring, vendeur+" ", "00x xxxxxxx", jLabel8.getText()+" DA", sdft.format(d) ,marchendise, jTextField5.getText()+" DA",jLabel19.getText() + " DA", jLabel21.getText(), db.Tel(),db.Addr());
            imprim.actionPerformed(evt);
        } catch (Exception ex) {
            Logger.getLogger(VenteForm2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{
            //--------------------------------------------------------
            db.UpdateQteResteAdd(DESIGNATION.get(Integer.parseInt(jTextField4.getText())),
                QTE.get(Integer.parseInt(jTextField4.getText()))     );
            db.AllStockVente(jTable1);
            //-------------------------------------------------------------
            DESIGNATION.remove(Integer.parseInt(jTextField4.getText()));
            PRIX.remove(Integer.parseInt(jTextField4.getText()));
            QTE.remove(Integer.parseInt(jTextField4.getText()));
            GAIN.remove(Integer.parseInt(jTextField4.getText()));
            Object  row1[] = new Object[4];
            Object  row2[] = new Object[2];
            mo1.setRowCount(0);
            mo2.setRowCount(0);
            ii=DESIGNATION.size()+1;int r=1;
            for(int i=0;i<DESIGNATION.size();i++){
                row1[0]=  r++;
                row1[1]= DESIGNATION.get(i);
                row1[2]= PRIX.get(i);
                row1[3]= QTE.get(i);
                row2[0]=GAIN.get(i);
                row2[1]=QTE.get(i);
                mo1.addRow(row1);
                mo2.addRow(row2);
            }

            jTextField4.setText("");
            FillArray(jTable2, jTable3, jLabel8, jLabel9, jTextField5.getText());
            jLabel19.setText(""+tva);
            String remise=jTextField5.getText();
            if("".equals(remise)){remise="0.0";}
            float total =Float.parseFloat(jLabel8.getText())+Float.parseFloat(remise)-Float.parseFloat(jLabel19.getText());
            jLabel21.setText(total+" DA");

        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "ereur operation"," ereur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{ if (JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer tout le tableau de ticket ?", "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
            {
                mo1.setRowCount(0);
                mo2.setRowCount(0);
                ii=1;
                DESIGNATION.clear();
                PRIX.clear();
                QTE.clear();
                GAIN.clear();
                jTextField4.setText("");
                jLabel8.setText("0.0");
                jLabel9.setText("0.0");}
        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(null,
                "ereur operation"," ereur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{

            if(jCheckBox1.isSelected()){
                fillTable(jTable1.getValueAt(count, 1)+"",Float.parseFloat(jTable1. getValueAt(count, 7)+""),
                    Integer.parseInt( jSpinner1.getValue().toString()),(Float.parseFloat(jTable1. getValueAt(count, 5 )+"")-Float.parseFloat(jTable1. getValueAt(count, 7)+"")),
                    jTable2, jTable3);}
            else{fillTable(jTable1.getValueAt(count, 1)+"",Float.parseFloat(jTable1. getValueAt(count, 5)+""),
                Integer.parseInt( jSpinner1.getValue().toString()),Float.parseFloat(jTable1. getValueAt(count, 6)+""),
                jTable2, jTable3);}
        db.UpdateQteResteMinus((int) jTable1.getValueAt(count, 0),Integer.parseInt(jSpinner1.getValue().toString()));
        db.AllStockVente(jTable1);
        FillArray(jTable2, jTable3, jLabel8, jLabel9, jTextField5.getText());
        jLabel19.setText(""+tva);
        String remise=jTextField5.getText();
        if("".equals(remise)){remise="0.0";}
        float total =Float.parseFloat(jLabel8.getText())+Float.parseFloat(remise)-Float.parseFloat(jLabel19.getText());
        jLabel21.setText(total+" DA");

        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "ereur operation"," ereur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        jTextField4.setText(jTable2.getSelectedRow()+"");
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        db.AllStockVente(jTable1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        if("".equals(jTextField1.getText())){
            db.AllStockVente(jTable1);
        }else{
            db.AllStockVenteRcherche(jTable1, jTextField1.getText());
        }

    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        db.AllStockVenteRcherche(jTable1, jTextField1.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        count = jTable1.getSelectedRow();
        // jTextField2.setText(jTable1.getValueAt(count, 0) + "");

    }//GEN-LAST:event_jTable1MouseClicked
int I;  private void BarcodeKeyTyped(java.awt.event.KeyEvent evt) {                                 

    }
  
   private void BarcodeKeyPressed(java.awt.event.KeyEvent evt) {                                   
       
    }     
  
  
  
  
       
    
    String marchendise;
    void FillArray (JTable T,JTable T2,JLabel j1,JLabel j2 , String f){
    DESIGNATION.clear();QTE.clear();PRIX.clear();GAIN.clear();
    marchendise="";int temp=0;
            float somePrix=0;
            float someGain=0;
            if("".equals(f)){f="0";}
    for(int i=0;i<T.getRowCount();i++){
        DESIGNATION.add((String)T.getValueAt(i, 1));
        QTE.add((int)T.getValueAt(i, 3));
        PRIX.add((float)T.getValueAt(i, 2));
        GAIN.add((float)T2.getValueAt(i, 0));
        somePrix=QTE.get(i)*PRIX.get(i)+somePrix;
        someGain=QTE.get(i)*GAIN.get(i)+someGain;
        temp=temp+1;
          marchendise=marchendise+"N° "+temp+" DES : "+DESIGNATION.get(i)+" pr : "+PRIX.get(i)
              +" qte : "+QTE.get(i)+ "\n"    ;    
    }
    tva = db.TVA()*(somePrix - Float.parseFloat(f))/100;
    j1.setText((somePrix - Float.parseFloat(f)+tva)+"");
    j2.setText((someGain - Float.parseFloat(f)+tva)+"");
}
DefaultTableModel mo1;
DefaultTableModel mo2;
    int ii=1;
    ArrayList<String> DESIGNATION;
    ArrayList<Float> PRIX;
    ArrayList<Integer> QTE;
    ArrayList<Float> GAIN;
    void fillTable(String des,float prix,int qte,float gain,JTable t1,JTable t2){
     mo1 = (DefaultTableModel) t1.getModel();
     mo2 = (DefaultTableModel) t2.getModel();
               Object  row1[] = new Object[4];
               Object  row2[] = new Object[2];
                DESIGNATION.add(des);
                PRIX.add(prix);
                QTE.add(qte);
                GAIN.add(gain);
             //  for(int i=0;i<DESIGNATION.size();i++){
         row1[0]=   ii++;  
         row1[1]= des;
         row1[2]= prix;
         row1[3]= qte;
         row2[0]=gain;
         row2[1]=qte;
         mo1.addRow(row1);
         mo2.addRow(row2);  
           //     }
         
         
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenteForm().setVisible(true);
                 
                   
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
